# Generated by Django 4.2.1 on 2023-08-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeOasis', '0002_bike_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='torque',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bike',
            name='weight',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bike',
            name='engine',
            field=models.CharField(max_length=20),
        ),
    ]
