# Generated by Django 4.2.1 on 2023-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeOasis', '0003_bike_torque_bike_weight_alter_bike_engine'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='name',
            new_name='make',
        ),
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
