# Generated by Django 4.2.1 on 2023-08-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BikeOasis', '0004_rename_name_bike_make_bike_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='torque',
            field=models.CharField(max_length=50),
        ),
    ]
